version: "3"
services:
  web:
    container_name: nuxt-app
    build: .
    ports:
      - 3000:3000
    working_dir: /use/local/src
    volumes:
      - .:/usr/local/src
      - node_modules_volume:/usr/local/src/node_modules
    tty: true

volumes:
  node_modules_volume:
    name: nuxt_app_node_modules_volume
