version: "3"
services:
  web:
    container_name: nuxt-app-test
    image: node:14.17.0
    ports:
      - 4000:4000
    environment:
      HOST: 0.0.0.0
      PORT: 4000
    working_dir: /usr/local/src
    volumes:
      - .:/usr/local/src
      - node_modules_volume:/usr/local/src/node_modules
    command: yarn dev

volumes:
  node_modules_volume:
    name: nuxt_app_node_modules_volume
