version: "3"
services:
  web:
    container_name: nuxt-app
    image: node:14.17.0
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    working_dir: /usr/local/src
    volumes:
      - .:/usr/local/src
      - node_modules_volume:/usr/local/src/node_modules

volumes:
  node_modules_volume:
    name: nuxt_app_node_modules_volume
